# Generated by Django 4.2.2 on 2024-02-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_student_password_remove_teacher_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='file',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(default=2345, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='app.project', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default=1234, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Electronic', 'Electronic'), ('Mechatronic', 'Mechatronic'), ('Electrical', 'Electrical')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineerin'), ('Science', 'Science'), ('Education', 'Education'), ('Accountancy', 'Accountancy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Electronic', 'Electronic'), ('Mechatronic', 'Mechatronic'), ('Electrical', 'Electrical')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineerin'), ('Science', 'Science'), ('Education', 'Education'), ('Accountancy', 'Accountancy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
