# Generated by Django 4.2.2 on 2024-02-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_file_alter_file_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Science', 'Science'), ('Education', 'Education'), ('Accountancy', 'Accountancy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Science', 'Science'), ('Education', 'Education'), ('Accountancy', 'Accountancy')], max_length=255, null=True),
        ),
    ]
