# Generated by Django 4.2.2 on 2024-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_type_alter_project_tag_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[('2563', '2562'), ('2564', '2564'), ('2565', '2565'), ('2566', '2566'), ('2567', '2567'), ('2568', '2568')], default=2566, max_length=255),
            preserve_default=False,
        ),
    ]
